"use client";

import { useState, useEffect, FormEvent } from "react";
import { useRouter } from "next/navigation";
import { Asset, AssetStatus } from "@/types";
import { useAssets } from "@/lib/assetStore";
import { useBranches } from "@/lib/branchStore";
import { useCategories } from "@/lib/categoryStore";

const STATUSES: AssetStatus[] = ["사용중", "보관중", "수리중", "폐기"];

// 품명 → 자산번호 접두어 매핑
const NAME_PREFIX_MAP: Record<string, string> = {
  "노트북": "NB",
  "모니터": "MN",
  "책상": "DK",
  "의자": "CH",
  "복합기": "MF",
  "프린터": "PR",
  "서버": "SV",
  "스캐너": "SC",
  "빔프로젝터": "PJ",
  "프로젝터": "PJ",
  "냉장고": "RF",
  "에어컨": "AC",
  "TV": "TV",
  "화이트보드": "WB",
  "소파": "SF",
  "사물함": "LK",
  "키보드": "KB",
  "마우스": "MS",
  "태블릿": "TB",
  "카메라": "CM",
  "전화기": "PH",
  "책장": "BS",
  "캐비닛": "CB",
};

function suggestPrefix(name: string): string {
  const trimmed = name.trim();
  if (!trimmed) return "";
  if (NAME_PREFIX_MAP[trimmed]) return NAME_PREFIX_MAP[trimmed];
  for (const [key, prefix] of Object.entries(NAME_PREFIX_MAP)) {
    if (trimmed.includes(key)) return prefix;
  }
  // 매핑 없으면 앞 2글자 대문자
  return trimmed.slice(0, 2).toUpperCase();
}

function generateNextNumber(prefix: string, existingAssets: Asset[], currentId?: string): string {
  if (!prefix) return "";
  const pattern = new RegExp(`^${prefix}-(\\d+)$`);
  const numbers = existingAssets
    .filter((a) => a.id !== currentId)
    .map((a) => {
      const match = a.assetNumber.match(pattern);
      return match ? parseInt(match[1], 10) : 0;
    })
    .filter((n) => n > 0);
  const next = numbers.length > 0 ? Math.max(...numbers) + 1 : 1;
  return `${prefix}-${String(next).padStart(3, "0")}`;
}

interface AssetFormProps {
  asset?: Asset;
}

export default function AssetForm({ asset }: AssetFormProps) {
  const isEdit = !!asset;
  const router = useRouter();
  const { assets, addAsset, updateAsset } = useAssets();
  const { branches } = useBranches();
  const { categories } = useCategories();

  const [name, setName] = useState(asset?.name ?? "");
  const [prefix, setPrefix] = useState(() => {
    if (asset) {
      // 기존 자산번호에서 접두어 추출 (NB-001 → NB)
      const match = asset.assetNumber.match(/^([A-Z]+)-\d+$/);
      return match ? match[1] : suggestPrefix(asset.name);
    }
    return "";
  });
  const [assetNumber, setAssetNumber] = useState(asset?.assetNumber ?? "");
  const [autoGenerated, setAutoGenerated] = useState(!isEdit);
  const [category, setCategory] = useState(asset?.category ?? categories[0]?.name ?? "");
  const [branchId, setBranchId] = useState(asset?.branchId ?? branches[0]?.id ?? "");
  const [status, setStatus] = useState<AssetStatus>(asset?.status ?? "사용중");
  const [purchaseDate, setPurchaseDate] = useState(asset?.purchaseDate ?? new Date().toISOString().split("T")[0]);
  const [note, setNote] = useState(asset?.note ?? "");
  const [errors, setErrors] = useState<Record<string, string>>({});

  // 품명 변경 시 접두어 자동 제안 (신규 등록만)
  useEffect(() => {
    if (!isEdit && name) {
      const suggested = suggestPrefix(name);
      setPrefix(suggested);
    }
  }, [name, isEdit]);

  // 접두어 변경 시 자산번호 자동 생성
  useEffect(() => {
    if (autoGenerated && prefix) {
      setAssetNumber(generateNextNumber(prefix, assets, asset?.id));
    }
  }, [prefix, autoGenerated, assets, asset?.id]);

  function handleNameChange(val: string) {
    setName(val);
  }

  function handlePrefixChange(val: string) {
    setPrefix(val.toUpperCase());
    setAutoGenerated(true);
  }

  function validate(): boolean {
    const e: Record<string, string> = {};
    if (!name.trim()) e.name = "품명을 입력해 주세요.";
    if (!assetNumber.trim()) e.assetNumber = "자산번호를 확인해 주세요.";
    if (!purchaseDate) e.purchaseDate = "구매일을 입력해 주세요.";
    setErrors(e);
    return Object.keys(e).length === 0;
  }

  function handleSubmit(e: FormEvent) {
    e.preventDefault();
    if (!validate()) return;

    const payload = {
      assetNumber: assetNumber.trim(),
      name: name.trim(),
      category,
      branchId,
      status,
      purchaseDate,
      note: note.trim(),
    };

    if (isEdit) {
      updateAsset(asset.id, payload);
    } else {
      addAsset(payload);
    }
    router.push("/assets");
  }

  return (
    <form onSubmit={handleSubmit} className="space-y-5">
      {/* 품명 */}
      <div>
        <label className="block text-sm font-medium text-gray-700 mb-1">
          품명 <span className="text-red-500">*</span>
        </label>
        <input
          type="text"
          value={name}
          onChange={(e) => handleNameChange(e.target.value)}
          placeholder="예: 노트북, 모니터, 책상"
          className={`w-full border rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-300 ${
            errors.name ? "border-red-400" : "border-gray-200"
          }`}
        />
        {errors.name && <p className="text-xs text-red-500 mt-1">{errors.name}</p>}
      </div>

      {/* 자산번호 자동 생성 */}
      <div className="bg-gray-50 border border-gray-200 rounded-lg p-4 space-y-3">
        <p className="text-xs font-medium text-gray-500">자산번호 설정</p>
        <div className="grid grid-cols-2 gap-3">
          <div>
            <label className="block text-xs text-gray-500 mb-1">접두어 (자동 제안)</label>
            <input
              type="text"
              value={prefix}
              onChange={(e) => handlePrefixChange(e.target.value)}
              placeholder="NB"
              maxLength={4}
              className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm font-mono focus:outline-none focus:ring-2 focus:ring-blue-300 uppercase"
            />
          </div>
          <div>
            <label className="block text-xs text-gray-500 mb-1">
              생성된 자산번호
              {autoGenerated && (
                <span className="ml-1 text-blue-500">(자동)</span>
              )}
            </label>
            <div className="flex gap-1">
              <input
                type="text"
                value={assetNumber}
                onChange={(e) => { setAssetNumber(e.target.value); setAutoGenerated(false); }}
                placeholder="NB-001"
                className={`flex-1 border rounded-lg px-3 py-2 text-sm font-mono focus:outline-none focus:ring-2 focus:ring-blue-300 ${
                  errors.assetNumber ? "border-red-400" : "border-gray-200"
                } ${autoGenerated ? "bg-blue-50 text-blue-700" : ""}`}
              />
              {!autoGenerated && (
                <button
                  type="button"
                  onClick={() => setAutoGenerated(true)}
                  className="text-xs text-blue-600 hover:underline whitespace-nowrap px-1"
                >
                  재생성
                </button>
              )}
            </div>
          </div>
        </div>
        {errors.assetNumber && <p className="text-xs text-red-500">{errors.assetNumber}</p>}
        <p className="text-xs text-gray-400">
          접두어를 수정하면 해당 접두어의 다음 순번으로 자동 채번됩니다. 자산번호를 직접 수정할 수도 있습니다.
        </p>
      </div>

      {/* 카테고리 + 지사 */}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">
            카테고리 <span className="text-red-500">*</span>
          </label>
          <select
            value={category}
            onChange={(e) => setCategory(e.target.value)}
            className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-300"
          >
            {categories.map((c) => (
              <option key={c.id} value={c.name}>{c.name}</option>
            ))}
          </select>
        </div>
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">
            현재 지사 <span className="text-red-500">*</span>
          </label>
          <select
            value={branchId}
            onChange={(e) => setBranchId(e.target.value)}
            className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-300"
          >
            {branches.map((b) => (
              <option key={b.id} value={b.id}>{b.name}</option>
            ))}
          </select>
        </div>
      </div>

      {/* 상태 + 구매일 */}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">
            상태 <span className="text-red-500">*</span>
          </label>
          <div className="flex gap-2 flex-wrap">
            {STATUSES.map((s) => (
              <button
                key={s}
                type="button"
                onClick={() => setStatus(s)}
                className={`px-3 py-1.5 rounded-lg text-sm font-medium border transition-colors ${
                  status === s
                    ? "bg-blue-600 text-white border-blue-600"
                    : "bg-white text-gray-600 border-gray-200 hover:border-blue-300"
                }`}
              >
                {s}
              </button>
            ))}
          </div>
        </div>
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">
            구매일 <span className="text-red-500">*</span>
          </label>
          <input
            type="date"
            value={purchaseDate}
            onChange={(e) => setPurchaseDate(e.target.value)}
            className={`w-full border rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-300 ${
              errors.purchaseDate ? "border-red-400" : "border-gray-200"
            }`}
          />
          {errors.purchaseDate && <p className="text-xs text-red-500 mt-1">{errors.purchaseDate}</p>}
        </div>
      </div>

      {/* 비고 */}
      <div>
        <label className="block text-sm font-medium text-gray-700 mb-1">비고</label>
        <input
          type="text"
          value={note}
          onChange={(e) => setNote(e.target.value)}
          placeholder="메모 (선택)"
          className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-300"
        />
      </div>

      {/* 버튼 */}
      <div className="flex gap-3 pt-2">
        <button
          type="submit"
          className="flex-1 bg-blue-600 text-white rounded-lg px-4 py-2.5 text-sm font-semibold hover:bg-blue-700 transition-colors"
        >
          {isEdit ? "수정 완료" : "자산 등록"}
        </button>
        <button
          type="button"
          onClick={() => router.back()}
          className="flex-1 bg-gray-100 text-gray-700 rounded-lg px-4 py-2.5 text-sm font-semibold hover:bg-gray-200 transition-colors"
        >
          취소
        </button>
      </div>
    </form>
  );
}
